/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.Color;
import java.rmi.RemoteException;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import models.Sala;
import models.TuplaEspecial;
import models.Usuario;
import net.jini.core.entry.UnusableEntryException;
import net.jini.core.lease.Lease;
import net.jini.core.transaction.TransactionException;
import net.jini.space.JavaSpace;

/**
 *
 * @author elysson
 */
public class SalasListagem extends javax.swing.JFrame {
    
    private JavaSpace space;
    private Usuario usuario;
    private Sala sala;
    private DefaultListModel listaSalas = null;
    private DefaultListModel listaUsuarios = null;
    
    /**
     * Creates new form SalasListagem
     */
    public SalasListagem() {
        initComponents();
    }
    
    public SalasListagem(Usuario usuario, JavaSpace space) throws ClassNotFoundException {
        initComponents();
        
        this.space = space;
        this.usuario = usuario;
        
        listaSalas = new DefaultListModel();
        listaUsuarios = new DefaultListModel();
        
        buscaSalas();
    }
    
    public void buscaSalas(){
        //DestinationSource destSource = connection.getDestinationSource();
        //Set<ActiveMQTopic> topicos = destSource.getTopics();
        
        TuplaEspecial template = new TuplaEspecial();
        TuplaEspecial t = null;
        try {
            t = (TuplaEspecial) space.read(template, null, 500);
        } catch (UnusableEntryException | TransactionException | InterruptedException | RemoteException ex) {
            Logger.getLogger(SalasListagem.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Sala salaTemplate = new Sala();
        Sala s = null;
        for (int i = 0; i < t.qtdSalas; i++) {
            try {
                salaTemplate.id = (i + 1);
                s = (Sala) space.read(salaTemplate, null, 500);
                listaSalas.addElement(s.nome);
            } catch (UnusableEntryException | TransactionException | InterruptedException | RemoteException ex) {
                Logger.getLogger(SalasListagem.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        this.jListSalas.setModel(listaSalas);
        //this.jListUsuarios.setModel(listaAssin);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonEntrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListUsuarios = new javax.swing.JList<>();
        jLabelNome1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListSalas = new javax.swing.JList<>();
        jLabelNome2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Chats Disponíveis");

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        jListUsuarios.setEnabled(false);
        jScrollPane1.setViewportView(jListUsuarios);

        jLabelNome1.setText("Nomes das salas:");

        jListSalas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListSalas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListSalasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListSalas);

        jLabelNome2.setText("Usuários presentes:");

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jButtonEntrar))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabelNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome1)
                    .addComponent(jLabelNome2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(jButtonEntrar)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        String select = this.jListSalas.getSelectedValue();
        
        if(select != null && !select.isEmpty()){
            
            Usuario u = null;
            Sala s = null;
            try {
                u = (Usuario) space.take(this.usuario, null, Lease.FOREVER);
                s = (Sala) space.take(this.sala, null, 500);
            } catch (UnusableEntryException | TransactionException | InterruptedException | RemoteException ex) {
                Logger.getLogger(SalaCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (u == null) {
                System.out.println("Tempo de espera esgotado. Encerrando...");
                System.exit(0);
            }
            u.sala = select;
            u.id = s.qtdUsu + 1;
            this.sala = s;
            this.sala.qtdUsu = u.id;
            
            try {
                this.space.write(this.sala, null, Lease.FOREVER);
                this.space.write(u, null, Lease.FOREVER);
            } catch (TransactionException | RemoteException ex) {
                Logger.getLogger(UsuarioCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            new Chat(this.usuario, this.space, this.sala).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jListSalasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListSalasValueChanged
        String select = this.jListSalas.getSelectedValue();
        listaUsuarios.removeAllElements();
        
        if(select != null && !select.isEmpty()){ 
            Sala s = null;
            Usuario uTemplate = new Usuario();
            uTemplate.sala = select;
            
            Usuario u = null;
            
            this.sala = new Sala();
            this.sala.nome = select;
            
            try {
                s = (Sala) space.read(this.sala, null, Lease.FOREVER);
            } catch (UnusableEntryException | TransactionException | InterruptedException | RemoteException ex) {
                Logger.getLogger(SalaCadastro.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            for (int i = 0; i < s.qtdUsu; i++) {
                try {
                    uTemplate.id = (i + 1);
                    u = (Usuario) space.read(uTemplate, null, 500);
                    listaUsuarios.addElement(u.nome);
                } catch (UnusableEntryException | TransactionException | InterruptedException | RemoteException ex) {
                    Logger.getLogger(SalasListagem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            this.jListUsuarios.setModel(listaUsuarios);
        }
    }//GEN-LAST:event_jListSalasValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalasListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalasListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalasListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalasListagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalasListagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelNome2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList<String> jListSalas;
    private javax.swing.JList<String> jListUsuarios;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
